default:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  tags:
  - ska-default

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  OCI_IMAGE_BUILD_CONTEXT: $(PWD)
  CI_POETRY_VERSION: 1.8.2
  DB_NAME: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: pass
  DB: db

# Enable caching for python
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
  - .cache/pip

stages:
- lint
- build
- test
- publish
- deploy
- delete
- pages
- scan


include:
# Python
- project: "ska-telescope/templates-repository"
  file: "gitlab-ci/includes/python.gitlab-ci.yml"
  # .post step finalisers eg: badges
- project: "ska-telescope/templates-repository"
  file: "gitlab-ci/includes/finaliser.gitlab-ci.yml"
# OCI
- project: "ska-telescope/templates-repository"
  file: "gitlab-ci/includes/oci-image.gitlab-ci.yml"
# Helm
- project: "ska-telescope/templates-repository"
  file: "gitlab-ci/includes/helm-chart.gitlab-ci.yml"
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/release.gitlab-ci.yml'
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/docs.gitlab-ci.yml'
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/tmdata.gitlab-ci.yml'

deploy:
  stage: deploy
  when: manual
  script:
  - helm upgrade --install my-release ./charts/ska-sdp-global-sky-model --namespace sdp-global-sky-model-integration --create-namespace
  tags:
  - ska-k8s

delete:
  stage: delete
  when: manual
  script:
  - helm delete my-release
  tags:
  - ska-k8s


services:
- name: artefact.skao.int/ska-sdp-global-sky-model-db:0.1.1
  alias: db
- name: redis:7.2.4
  alias: redis

