default:
  image: $SKA_K8S_TOOLS_BUILD_DEPLOY
  tags:
  - k8srunner

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  OCI_IMAGE_BUILD_CONTEXT: $(PWD)
  CI_POETRY_VERSION: 1.8.2
  DB_NAME: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: pass
  DB: db

# Enable caching for python
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
  - .cache/pip

stages:
- lint
- build
- test
- integration
- publish
- pages
- scan


include:
# Python
- project: "ska-telescope/templates-repository"
  file: "gitlab-ci/includes/python.gitlab-ci.yml"
  # .post step finalisers eg: badges
- project: "ska-telescope/templates-repository"
  file: "gitlab-ci/includes/finaliser.gitlab-ci.yml"
# OCI
- project: "ska-telescope/templates-repository"
  file: "gitlab-ci/includes/oci-image.gitlab-ci.yml"
# Helm
- project: "ska-telescope/templates-repository"
  file: "gitlab-ci/includes/helm-chart.gitlab-ci.yml"
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/release.gitlab-ci.yml'
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/docs.gitlab-ci.yml'
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/tmdata.gitlab-ci.yml'
# Deployment
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/deploy.gitlab-ci.yml'

.info_script: &info_script
- |-
  echo "Status of pods in $KUBE_NAMESPACE namespace:"
  kubectl get pods -n $KUBE_NAMESPACE -o jsonpath="{range .items[*]}{'Pod: '}{.metadata.name}:{'\n'}{'\t'}{'Image: '}{.spec.containers[*].image}{'\n'}{'\t'}{'Status: '}{.status.phase}{'\n'}{end}{'\n'}"
  echo "Addresses to connect to the deployment of the Dataproduct Dashboard: "
  echo "  https://sdhp.stfc.skao.int/$KUBE_NAMESPACE/global-sky-model/"


deploy-integration-to:
  stage: integration
  extends: deploy-integration
  when: manual
  tags:
  - ska-default
  variables:
    K8S_CHART_PARAMS: '--set api.vault.useVault=true --set api.vault.pathToSecretVault=kv/data/users/jm22b/ska_sdp_gsm --set api.postgresql.host=pgdev-lb.cnpgdev.svc.cluster.local'
    KUBE_NAMESPACE: 'sdp-global-sky-model-integration'

info-integration-to:
  stage: integration
  extends: info-integration
  tags:
  - ska-default
  script:
  - *info_script

redeploy-integration-to:
  stage: integration
  extends: redeploy-integration
  tags:
  - ska-default
  variables:
    K8S_CHART_PARAMS: '--set api.vault.useVault=true --set api.vault.pathToSecretVault=kv/data/users/jm22b/ska_sdp_gsm --set api.postgresql.host=pgdev-lb.cnpgdev.svc.cluster.local'
    KUBE_NAMESPACE: 'sdp-global-sky-model-integration'

stop-integration-to:
  stage: integration
  extends: stop-integration
  tags:
  - ska-default
  needs:
  - deploy-integration

services:
- name: artefact.skao.int/ska-sdp-global-sky-model-db:0.1.1
  alias: db
- name: redis:7.2.4
  alias: redis

