services:
  fastapi:
    build:
      context: images/ska-sdp-global-sky-model-api
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    links:
      - redis:redis

  db:
    build:
      context: images/ska-sdp-global-sky-model-db
      dockerfile: Dockerfile
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB:  'postgres'
    ports:
      - "5432:5432"
    volumes:
      - ./initdb-pgsphere.sh:/docker-entrypoint-initdb.d/initdb-pgsphere.sh
      - database_volume:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    environment:
      BITNAMI_DEBUG: "false"
      REDIS_REPLICATION_MODE: master
      ALLOW_EMPTY_PASSWORD: "yes"
      REDIS_TLS_ENABLED: "no"
      REDIS_PORT: 6379

volumes:
  database_volume:
    name: database_volume

networks:
  default:
    name: ska-sdp-global-sky-model
