services:
  fastapi:
    build:
      context: .
      dockerfile: images/ska-sdp-global-sky-model-api/Dockerfile
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./src/ska_sdp_global_sky_model:/usr/src/ska_sdp_global_sky_model
      - gsm_volume:/usr/src/ska_sdp_global_sky_model/datasets
    environment:
      API_VERBOSE: 'true'

volumes:
  gsm_volume:
    name: gsm_volume
