services:
  fastapi:
    build:
      context: .
      dockerfile: images/ska-sdp-global-sky-model-api/Dockerfile
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - db
    links:
      - redis:redis
      - db:db
    volumes:
      - ./src/ska_sdp_global_sky_model:/usr/src/ska_sdp_global_sky_model
    environment:
      API_VERBOSE: 'true'

  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB:  'postgres'
    ports:
      - "5432:5432"
    volumes:
      - database_volume:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"

volumes:
  database_volume:
    name: database_volume
