[tool.poetry]
include = ["MANIFEST.skao.int"]
name = "ska_sdp_global_sky_model"
version = "0.1.2-rcal"
description = ""
authors = ["Jacob Maresca <jacob.maresca@akkodis.com>"]
packages = [{include = "ska_sdp_global_sky_model", from = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.110.1"
sqlalchemy = "^2.0.29"
uvicorn = "^0.29.0"
sqlmodel = "^0.0.16"
sphinx = "^7.2.6"
flake8 = "^7.0.0"
httpx = "^0.27.0"
psycopg2-binary = "^2.9.9"
poetry-core = "^1.9.0"
healpix-alchemy = "^1.1.0"
astroquery = "^0.4.7"
ska-ser-logging = "^0.4.3"
mocpy = "^0.15.0"
cdshealpix = "^0.6.5"
orjson = "^3.10.6"


[tool.poetry.group.dev.dependencies]
isort = "^5.13.2"
black = "^24.3.0"
flake8 = "^7.0.0"
pylint = "^3.1.0"
pylint-junit = "^0.3.4"
pytest = "^8.1.1"
pytest-cov = "^5.0.0"
build = "^1.2.1"
psycopg2-binary = "^2.9.9"
alembic = "^1.13.2"


[tool.poetry.group.docs.dependencies]
sphinx = "^7.2.6"
sphinx-copybutton = "^0.5.2"
ska-ser-sphinx-theme = "^0.1.2"
sphinx-new-tab-link = "^0.4.0"



[[tool.poetry.source]]
name = "ska-nexus"
url = "https://artefact.skao.int/repository/pypi-internal/simple"
priority = "supplemental"


[[tool.poetry.source]]
name = "PyPI-public"
url = "https://pypi.org/simple"
priority = "primary"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

