# Configure a ClusterIP service for internal api access.
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    service: api
spec:
  selector:
    app: api
  ports:
  - port: 80

---

# Configure a deployment for the api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: jm222b/fastapi-demo
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
        ports:
        - containerPort: 80