
---

# Configure a NodePort service for access to the Redis Pod
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-session-db
spec:
  selector:
    service: {{ .Chart.Name }}-session-db
  ports:
  - port: {{ .Values.redisservice.port }}
    targetPort: {{ .Values.redisservice.nodePort }}

---

# Configure a deployment for our session db (Redis)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-session-db
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "ska-sdp-global-sky-model.labels" . | indent 6 }}
      app.kubernetes.io/name: {{ .Chart.Name }}-session-db
  template:
    metadata:
      labels:
{{ include "ska-sdp-global-sky-model.labels" . | indent 8 }}
        app.kubernetes.io/name: {{ .Chart.Name }}-session-db
    spec:
      containers:
      - name: {{ .Chart.Name }}-session-db
        image: redis:7.2.4
        ports:
        - containerPort: 6379