# Configure a persistent volume for postgres
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: local
spec:
  capacity:
    storage: 128M
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/db-pv"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128M
  volumeName: db-pv
  storageClassName: standard

---

# Configure a NodePort service for access to the Postgres Pod.
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    service: {{ .Release.Name }}-db
  type: {{ .Values.nodeportservice.type }}
  ports:
  - port: {{ .Values.nodeportservice.port }}
    nodePort: {{ .Values.nodeportservice.nodePort }}

---

# Configure a deployment for our postgres database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
  labels:
    name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-db
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.dbimage.repository}}:{{ .Values.dbimage.tag }}
        imagePullPolicy: {{ .Values.dbimage.pullPolicy }}
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-db-credentials
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-db-credentials
                key: password
        volumeMounts:
          - name: db-volume-mount
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-volume-mount
        persistentVolumeClaim:
          claimName: db-pvc
      restartPolicy: Always

---

# Configure a NodePort service for access to the Redis Pod
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-session-db
spec:
  selector:
    service: {{ .Release.Name }}-session-db
  type: {{ .Values.redisnodeportservice.type}}
  ports:
  - port: {{ .Values.redisnodeportservice.port }}
    nodePort: {{ .Values.redisnodeportservice.nodePort }}

---

# Configure a deployment for our session db (Redis)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-session-db
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Release.Name }}-session-db
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-session-db
    spec:
      containers:
      - name: {{ .Release.Name }}-session-db
        image: redis:5.0-alpine
        ports:
        - containerPort: 6379