apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{ include "ska-sdp-global-sky-model.labels" . | indent 4 }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
{{ include "ska-sdp-global-sky-model.labels" . | indent 4 }}
  name: {{ .Chart.Name }}-api
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: 80
        path: "{{ include "ska-sdp-global-sky-model.ingress_path_prepend" . }}/global-sky-model/(.*)"
        pathType: ImplementationSpecific
