replicaCount: 1

api:
  repository: artefact.skao.int/ska-sdp-global-sky-model-api
  tag: latest
  pullPolicy: Always

db:
  host: "10.100.10.46"

dbservice:
  port: 5432
  nodePort: 30001

redisservice:
  port: 6379
  nodePort: 30002


ingress:
  enabled: true
  pathStart: "/sdp"
  namespaced: true


env:
  name: dev

vault:
  useVault: true
  pathToSecretVault: kv/groups/ska-dev/naledi
