replicaCount: 1

api:
  repository: registry.gitlab.com/ska-telescope/sdp/ska-sdp-global-sky-model/ska-sdp-global-sky-model-api
  tag: 0.1.4-dev.c18311aa2
  pullPolicy: Always

db:
  host: "10.100.10.46"

dbservice:
  port: 5432
  nodePort: 30001

redisservice:
  port: 6379
  nodePort: 30002


ingress:
  enabled: true
  pathStart: "/sdp"
  namespaced: true


env:
  name: dev

vault:
  useVault: true
  pathToSecretVault: kv/users/jm22b/ska_sdp_gsm
