replicaCount: 1

env:
  verbose: false
  tmdata_source: ""
  tmdata_keys: ""
  nside: 128

api:
  repository: artefact.skao.int/ska-sdp-global-sky-model-api
  tag: latest
  pullPolicy: Always

ingress:
  enabled: true
  pathStart: "/sdp"
  namespaced: true

volume:
  size: 10Gi
  storageClassName: nfss1