replicaCount: 1

api:
  repository: jm222b/fastapi-demo
  tag: "latest"
  pullPolicy: Always

dbimage:
  repository: jm222b/ska-gsm-db
  tag: "latest"
  pullPolicy: Always

nodeportservice:
  type: NodePort
  port: 5432
  nodePort: 30001

redisnodeportservice:
  type: NodePort
  port: 6379
  nodePort: 30002

loadbalancerservice:
  type: LoadBalancer
  port: 80
  targetPort: 80

persistentvolume:
  storageclassname: standard
  size: 128M
  accessmodes: ReadWriteOnce
  hostpath: "/data/db-pv"

env:
  name: dev